### ISSUE TITLE
Sobran todos los for. Usad la API de ArrayList

### ISSUE THREAD

**Issue by lmagarin** [gfAlvaro/Java#5]
https://github.com/gfAlvaro/Java/blob/7c8403b545b1ebb6354351f254a618e989c80bc9/ObjetosJava3/GESTIMAL-master/src/GESTIMALMejorado/Almacen.java#L33

**Comment by gfAlvaro** [comment]
Revisado.

**Comment by lmagarin** [comment]
Vuelve a abrir este issue porque sigues sin usar el arrayList en toda su potencia
