### ISSUE TITLE
Sobran...

### ISSUE THREAD

**Issue by lmagarin** [gfAlvaro/Java#9]
https://github.com/gfAlvaro/Java/blob/7c8403b545b1ebb6354351f254a618e989c80bc9/ObjetosJava3/GESTIMAL-master/src/GESTIMALMejorado/Almacen.java#L32
Sobra for
Sobra comunicación con el usuario
Sustituidlo por 
`return arrayList.remove(new Articulo(codigo));`

**Comment by gfAlvaro** [comment]
Revisar.
